spring.application.name=payment-ms
server.port=9088

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Demo audit file. Can override using PAYMENT_AUDIT_LOG_FILE env variable.
payment.audit.log-file=${PAYMENT_AUDIT_LOG_FILE:logs/gateway_audit.log}

# Deliberately missing SWIFT_INTL to trigger runtime failure for auto-healing demo.
payment.fees.DOMESTIC=0.02
payment.fees.ACH=0.01

payment.tax-rate=0.05
